# Generated by Django 3.2.7 on 2021-10-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkprinters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_details_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='domain_details_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_validate_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='job_portal_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='person_details_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
